import Foundation

enum GreekLetters: String {
    case mathematicalBoldCapitalDelta = "\u{1D6AB}"
    case mathematicalBoldSmallDelta = "\u{1D6C5}"
    case mathematicalItalicCapitalDelta = "\u{1D6E5}"
    case mathematicalItalicSmallDelta = "\u{1D6FF}"
    case mathematicalBoldCapitalOmicron = "\u{1D6B6}"
    case mathematicalBoldSmallOmicron = "\u{1D6D0}"
    case mathematicalItalicCapitalOmicron = "\u{1D6F0}"
    case mathematicalItalicSmallOmicron = "\u{1D70A}"
    case mathematicalBoldCapitalGamma = "\u{1D6AA}"
    case mathematicalBoldSmallGamma = "\u{1D6C4}"
    case mathematicalItalicCapitalGamma = "\u{1D6E4}"
    case mathematicalItalicSmallGamma = "\u{1D6FE}"
    case mathematicalBoldCapitalEta = "\u{1D6AE}"
    case mathematicalBoldSmallEta = "\u{1D6C8}"
    case mathematicalItalicCapitalEta = "\u{1D6E8}"
    case mathematicalItalicSmallEta = "\u{1D702}"
    case mathematicalBoldCapitalNu = "\u{1D6B4}"
    case mathematicalBoldSmallNu = "\u{1D6CE}"
    case mathematicalItalicCapitalNu = "\u{1D6EE}"
    case mathematicalItalicSmallNu = "\u{1D708}"
    case mathematicalBoldCapitalMu = "\u{1D6B3}"
    case mathematicalBoldSmallMu = "\u{1D6CD}"
    case mathematicalItalicCapitalMu = "\u{1D727}"
    case mathematicalItalicSmallMu = "\u{1D741}"
    case mathematicalBoldCapitalRho = "\u{1D40F}"
    case mathematicalBoldSmallRho = "\u{1D6D2}"
    case mathematicalItalicCapitalRho = "\u{1D477}"
    case mathematicalItalicSmallRho = "\u{1D746}"
    case mathematicalBoldCapitalTau = "\u{1D6BB}"
    case mathematicalBoldSmallTau = "\u{1D6D5}"
    case mathematicalItalicCapitalTau = "\u{1D72F}"
    case mathematicalItalicSmallTau = "\u{1D749}"
    case levelLeft = "\u{230A}"
    case levelRight = "\u{230B}"
}
